using UnityEngine;
using System;
using System.Text;
using System.Collections;

public static class iCS_CSFileTemplates {
    // ----------------------------------------------------------------------
    public static string FileHeader(string fileName, string className, string author= null) {
        var bar= "/////////////////////////////////////////////////////////////////\n";
        var h1=  "//  "+fileName+"\n"+
                 "//\n";
        var h2=  "//  Generated by iCanScript v"+iCS_EditorConfig.VersionId+"\n"+
                 "//  Created on: "+DateTime.Now+"\n";
        var h3=  author == null ?
                 "" :
                 "//  Original author: "+author+"\n";
        return bar+h1+h2+h3+bar;
    } 

}
