cp -r ../Assets/iCanScript/Engine/Runtime/Functions/_NET/_NET_Variables.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/_NET/_NET_Variables.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_Conversions.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_Conversions.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_CosWave.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_CosWave.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_GameController.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_GameController.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_GameObject.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_GameObject.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_Logic.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_Logic.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_Math3D.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_Math3D.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_SinWave.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_SinWave.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCanScript/iCS_Time.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCanScript/iCS_Time.cs
cp -r ../Assets/iCanScript/Engine/Runtime/Functions/iCS_TestFunction.cs ../../iCanScriptPublish/Assets/iCanScript/Functions/iCS_TestFunction.cs
