/////////////////////////////////////////////////////////////////
//  MainCameraBehaviour_6812.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 06/29/2013 11:27:44
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class MainCameraBehaviour_6812 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

}
