/////////////////////////////////////////////////////////////////
//  MainCameraBehaviour_6960.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/03/2013 20:31:13
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class MainCameraBehaviour_6960 : MonoBehaviour {
	iCS_VisualScript   myVisualScript= null;

	void Start()
	{
		myVisualScript= GetComponent(typeof(iCS_VisualScript)) as iCS_VisualScript;
	}

	void Update()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("Update");
		}
	}


}
