/////////////////////////////////////////////////////////////////
//  SphereBehaviourProxy_6836.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/02/2013 17:34:47
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviourProxy_6836 : MonoBehaviour {
	iCS_VisualScript   myVisualScript= null;

	void Start()
	{
		myVisualScript= GetComponent(typeof(iCS_VisualScript)) as iCS_VisualScript;
	}

	void Update()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("Update");
		}
	}


	void LateUpdate()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("LateUpdate");
		}
	}


}
