/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6930.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 06/28/2013 22:06:26
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6930 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseOver()
	{
		RunMessage("OnMouseOver");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

	void OnMouseEnter()
	{
		RunMessage("OnMouseEnter");
	}

}
