/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6970.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/03/2013 20:30:36
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6970 : MonoBehaviour {
	iCS_VisualScript   myVisualScript= null;

	void Start()
	{
		myVisualScript= GetComponent(typeof(iCS_VisualScript)) as iCS_VisualScript;
	}

	void Update()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("Update");
		}
	}


	void LateUpdate()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("LateUpdate");
		}
	}


}
