/////////////////////////////////////////////////////////////////
//  SphereBehaviourProxy_6824.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/03/2013 15:09:50
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviourProxy_6824 : MonoBehaviour {
	iCS_VisualScript   myVisualScript= null;

	void Start()
	{
		myVisualScript= GetComponent(typeof(iCS_VisualScript)) as iCS_VisualScript;
	}

	void Update()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("Update");
		}
	}


	void LateUpdate()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("LateUpdate");
		}
	}


	void FixedUpdate()
	{
		if(myVisualScript != null) {
			myVisualScript.RunMessage("FixedUpdate");
		}
	}


}
