/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6840.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/02/2013 10:11:58
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6840 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseOver()
	{
		RunMessage("OnMouseOver");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

	void OnMouseUpAsButton()
	{
		RunMessage("OnMouseUpAsButton");
	}

}
