/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6840.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/02/2013 13:52:51
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6840 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseOver()
	{
		RunMessage("OnMouseOver");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

	void OnBecameVisible()
	{
		RunMessage("OnBecameVisible");
	}

	void OnMouseEnter()
	{
		RunMessage("OnMouseEnter");
	}

}
