/////////////////////////////////////////////////////////////////
//  SphereBehaviourProxy_6840.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/02/2013 16:51:13
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviourProxy_6840 : MonoBehaviour {
	iCS_Behaviour   myBehaviour= null;

	void Start()
	{
		myBehaviour= GetComponent(typeof(iCS_Behaviour)) as iCS_Behaviour;
	}

	void Update()
	{
		if(myBehaviour != null) {
			myBehaviour.RunMessage("Update");
		}
	}


	void LateUpdate()
	{
		if(myBehaviour != null) {
			myBehaviour.RunMessage("LateUpdate");
		}
	}


	void FixedUpdate()
	{
		if(myBehaviour != null) {
			myBehaviour.RunMessage("FixedUpdate");
		}
	}



}
