/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6806.cs
//
//  Implementation of SphereBehaviour_6806
//  Generated by iCanScript v0.9.3
//  Created on: 06/27/2013 10:04:30
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6806 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseOver()
	{
		RunMessage("OnMouseOver");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

}
