/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6814.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 06/28/2013 21:38:53
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6814 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

}
