/////////////////////////////////////////////////////////////////
//  SphereBehaviour_6824.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 06/29/2013 10:40:47
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class SphereBehaviour_6824 : iCS_BehaviourImp {

	void Update()
	{
		RunMessage("Update");
	}

	void OnMouseOver()
	{
		RunMessage("OnMouseOver");
	}

	void OnMouseExit()
	{
		RunMessage("OnMouseExit");
	}

	void OnMouseEnter()
	{
		RunMessage("OnMouseEnter");
	}

}
