///////////////////////////////////////////////////////////
//  SSRunState.cs
//  Implementation of the Class SSRunState
//  Generated by Enterprise Architect
//  Created on:      11-Feb-2015 4:09:45 PM
//  Original author: Reinual
///////////////////////////////////////////////////////////




namespace Subspace {
	public enum SSRunState : int {

		WAITING,
		DISABLED,
		RAN

	}//end SSRunState

}//end namespace Subspace