///////////////////////////////////////////////////////////
//  SSContext.cs
//  Implementation of the Class SSContext
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2015 11:01:08 AM
//  Original author: Reinual
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;


namespace Subspace {

    public class SSContext {
        // ======================================================================
        // Fields
        // ----------------------------------------------------------------------
        Object myUserData	   = null;
    	bool   myIsTraceEnabled= false;

        // ======================================================================
        // Properties
        // ----------------------------------------------------------------------
        public bool IsTraceEnabled {
            get { return myIsTraceEnabled; }
            set { myIsTraceEnabled= value; }
        }
        public Object UserData {
            get { return myUserData; }
        }
        
        // ======================================================================
        // Constructor/Destructor
        // ----------------------------------------------------------------------
        public SSContext(Object userData= null) {
            myUserData= userData;
        }
        
    }//end SSContext    

}
