///////////////////////////////////////////////////////////
//  SSContext.cs
//  Implementation of the Class SSContext
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2015 11:01:08 AM
//  Original author: Reinual
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;


namespace Subspace {

    public class SSContext {
        // ======================================================================
        // Fields
        // ----------------------------------------------------------------------
        iCS_VisualScriptImp myVisualScript= null;
    	bool                myIsTraceEnabled = false;

        // ======================================================================
        // Properties
        // ----------------------------------------------------------------------
        public bool IsTraceEnabled {
            get { return myIsTraceEnabled; }
            set { myIsTraceEnabled= value; }
        }
        public iCS_VisualScriptImp VisualScript {
            get { return myVisualScript; }
        }
        
        // ======================================================================
        // Constructor/Destructor
        // ----------------------------------------------------------------------
        public SSContext(iCS_VisualScriptImp visualScript) {
            myVisualScript= visualScript;
        }
        
    }//end SSContext    

}
