/////////////////////////////////////////////////////////////////
//  iCS_Behaviour.cs
//
//  Generated by iCanScript v0.9.3
//  Created on: 07/05/2013 12:05:49
/////////////////////////////////////////////////////////////////

using UnityEngine;

public sealed class iCS_Behaviour : MonoBehaviour {
	iCS_VisualScript[]   allVisualScripts= new iCS_VisualScript[0];

	void Start()
	{
		allVisualScripts= FindObjectsOfType(typeof(iCS_VisualScript)) as iCS_VisualScript[];
	}

	void Update()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("Update");
		}
	}


	void LateUpdate()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("LateUpdate");
		}
	}


	void FixedUpdate()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("FixedUpdate");
		}
	}



	void Reset()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("Reset");
		}
	}


	void OnMouseEnter()
	{
		Debug.Log("OnMouseEnter");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseEnter");
		}
	}


	void OnMouseOver()
	{
		Debug.Log("OnMouseOver");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseOver");
		}
	}


	void OnMouseExit()
	{
		Debug.Log("OnMouseExit");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseExit");
		}
	}


	void OnMouseDown()
	{
		Debug.Log("OnMouseDown");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseDown");
		}
	}


	void OnMouseUp()
	{
		Debug.Log("OnMouseUp");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseUp");
		}
	}


	void OnMouseUpAsButton()
	{
		Debug.Log("OnMouseUpAsButton");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseUpAsButton");
		}
	}


	void OnMouseDrag()
	{
		Debug.Log("OnMouseDrag");
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMouseDrag");
		}
	}


	void OnBecameVisible()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnBecameVisible");
		}
	}


	void OnBecameInvisible()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnBecameInvisible");
		}
	}


	void OnEnable()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnEnable");
		}
	}


	void OnDisable()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnDisable");
		}
	}


	void OnDestroy()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnDestroy");
		}
	}


	void OnPreCull()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnPreCull");
		}
	}


	void OnPreRender()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnPreRender");
		}
	}


	void OnPostRender()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnPostRender");
		}
	}


	void OnRenderObject()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnRenderObject");
		}
	}


	void OnWillRenderObject()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnWillRenderObject");
		}
	}


	void OnGUI()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnGUI");
		}
	}


	void OnDrawGizmosSelected()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnDrawGizmosSelected");
		}
	}


	void OnDrawGizmos()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnDrawGizmos");
		}
	}


	void OnServerInitialized()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnServerInitialized");
		}
	}


	void OnConnectedToServer()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnConnectedToServer");
		}
	}


	void OnAnimatorMove()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnAnimatorMove");
		}
	}


	void OnApplicationQuit()
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnApplicationQuit");
		}
	}


	void OnTriggerEnter(Collider other)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnTriggerEnter", other);
		}
	}


	void OnTriggerExit(Collider other)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnTriggerExit", other);
		}
	}


	void OnTriggerStay(Collider other)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnTriggerStay", other);
		}
	}


	void OnCollisionEnter(Collision collisionInfo)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnCollisionEnter", collisionInfo);
		}
	}


	void OnCollisionExit(Collision collisionInfo)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnCollisionExit", collisionInfo);
		}
	}


	void OnCollisionStay(Collision collisionInfo)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnCollisionStay", collisionInfo);
		}
	}


	void OnControllerColliderHit(ControllerColliderHit hit)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnControllerColliderHit", hit);
		}
	}


	void OnJointBreak(float breakForce)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnJointBreak", breakForce);
		}
	}


	void ParticleCollision(GameObject gameObject)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("ParticleCollision", gameObject);
		}
	}


	void OnLevelWasLoaded(int level)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnLevelWasLoaded", level);
		}
	}


	void OnApplicationPause(bool pause)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnApplicationPause", pause);
		}
	}


	void OnApplicationFocus(bool focus)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnApplicationFocus", focus);
		}
	}


	void OnPlayerConnected(NetworkPlayer player)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnPlayerConnected", player);
		}
	}


	void OnPlayerDisconnected(NetworkPlayer player)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnPlayerDisconnected", player);
		}
	}


	void OnDisconnectedFromServer(NetworkDisconnection mode)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnDisconnectedFromServer", mode);
		}
	}


	void OnFailedToConnect(NetworkConnectionError error)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnFailedToConnect", error);
		}
	}


	void OnFailedToConnectToMasterServer(NetworkConnectionError error)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnFailedToConnectToMasterServer", error);
		}
	}


	void OnMasterServerEvent(MasterServerEvent msEvent)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnMasterServerEvent", msEvent);
		}
	}


	void OnNetworkInstantiate(NetworkMessageInfo info)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnNetworkInstantiate", info);
		}
	}


	void OnSerializeNetworkView(BitStream stream, NetworkMessageInfo info)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnSerializeNetworkView", stream, info);
		}
	}


	void OnAnimatorIK(int layerIndex)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnAnimatorIK", layerIndex);
		}
	}


	void OnRenderImage(RenderTexture source, RenderTexture destination)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnRenderImage", source, destination);
		}
	}


	void OnAudioFilterRead(float[] data, int channels)
	{
		foreach(var vs in allVisualScripts) {
			vs.RunMessage("OnAudioFilterRead", data, channels);
		}
	}


}
