//{"ContentHash" : "96A1B63E312C706E12DDBE642F72E78D"}
/////////////////////////////////////////////////////////////////
//  iCS_Behaviour.cs
//
//  Generated by iCanScript v1.2.4
/////////////////////////////////////////////////////////////////

using UnityEngine;

[AddComponentMenu("")]
public sealed class iCS_Behaviour : MonoBehaviour {
	iCS_VisualScript[]   allVisualScripts= null;

	void Start()
	{
		allVisualScripts= gameObject.GetComponents<iCS_VisualScript>();
	}

	void FixedUpdate()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("FixedUpdate");
			}
		}
	}


	void LateUpdate()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("LateUpdate");
			}
		}
	}


	void OnApplicationFocus(bool focus)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnApplicationFocus", focus);
			}
		}
	}


	void OnApplicationPause(bool pause)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnApplicationPause", pause);
			}
		}
	}


	void OnApplicationQuit()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnApplicationQuit");
			}
		}
	}


	void OnAudioFilterRead(float[] data, int channels)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnAudioFilterRead", data, channels);
			}
		}
	}


	void OnBecameInvisible()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnBecameInvisible");
			}
		}
	}


	void OnBecameVisible()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnBecameVisible");
			}
		}
	}


	void OnCollisionEnter(Collision collisionInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnCollisionEnter", collisionInfo);
			}
		}
	}


	void OnCollisionExit(Collision collisionInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnCollisionExit", collisionInfo);
			}
		}
	}


	void OnCollisionStay(Collision collisionInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnCollisionStay", collisionInfo);
			}
		}
	}


	void OnConnectedToServer()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnConnectedToServer");
			}
		}
	}


	void OnControllerColliderHit(ControllerColliderHit hit)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnControllerColliderHit", hit);
			}
		}
	}


	void OnDestroy()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnDestroy");
			}
		}
	}


	void OnDisable()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnDisable");
			}
		}
	}


	void OnDisconnectedFromServer(NetworkDisconnection mode)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnDisconnectedFromServer", mode);
			}
		}
	}


	void OnDrawGizmos()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnDrawGizmos");
			}
		}
	}


	void OnDrawGizmosSelected()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnDrawGizmosSelected");
			}
		}
	}


	void OnEnable()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnEnable");
			}
		}
	}


	void OnFailedToConnect(NetworkConnectionError error)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnFailedToConnect", error);
			}
		}
	}


	void OnFailedToConnectToMasterServer(NetworkConnectionError error)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnFailedToConnectToMasterServer", error);
			}
		}
	}


	void OnGUI()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnGUI");
			}
		}
	}


	void OnJointBreak(float breakForce)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnJointBreak", breakForce);
			}
		}
	}


	void OnLevelWasLoaded(int level)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnLevelWasLoaded", level);
			}
		}
	}


	void OnMasterServerEvent(MasterServerEvent msEvent)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMasterServerEvent", msEvent);
			}
		}
	}


	void OnMouseDown()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseDown");
			}
		}
	}


	void OnMouseDrag()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseDrag");
			}
		}
	}


	void OnMouseEnter()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseEnter");
			}
		}
	}


	void OnMouseExit()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseExit");
			}
		}
	}


	void OnMouseOver()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseOver");
			}
		}
	}


	void OnMouseUp()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseUp");
			}
		}
	}


	void OnMouseUpAsButton()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnMouseUpAsButton");
			}
		}
	}


	void OnNetworkInstantiate(NetworkMessageInfo info)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnNetworkInstantiate", info);
			}
		}
	}


	void OnPlayerConnected(NetworkPlayer player)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnPlayerConnected", player);
			}
		}
	}


	void OnPlayerDisconnected(NetworkPlayer player)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnPlayerDisconnected", player);
			}
		}
	}


	void OnPostRender()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnPostRender");
			}
		}
	}


	void OnPreCull()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnPreCull");
			}
		}
	}


	void OnPreRender()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnPreRender");
			}
		}
	}


	void OnRenderImage(RenderTexture source, RenderTexture destination)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnRenderImage", source, destination);
			}
		}
	}


	void OnRenderObject()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnRenderObject");
			}
		}
	}


	void OnSerializeNetworkView(BitStream stream, NetworkMessageInfo info)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnSerializeNetworkView", stream, info);
			}
		}
	}


	void OnServerInitialized()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnServerInitialized");
			}
		}
	}


	void OnTriggerEnter(Collider colliderInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnTriggerEnter", colliderInfo);
			}
		}
	}


	void OnTriggerExit(Collider colliderInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnTriggerExit", colliderInfo);
			}
		}
	}


	void OnTriggerStay(Collider colliderInfo)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnTriggerStay", colliderInfo);
			}
		}
	}


	void OnWillRenderObject()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("OnWillRenderObject");
			}
		}
	}


	void ParticleCollision(GameObject gameObject)
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("ParticleCollision", gameObject);
			}
		}
	}


	void Reset()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("Reset");
			}
		}
	}



	void Update()
	{
		if(allVisualScripts != null) {
			foreach(var vs in allVisualScripts) {
				vs.RunMessage("Update");
			}
		}
	}


}
